-- Lilyum Design: authentication, private favorites, price tracking and owner-only catalog.
-- Run once in a new Supabase project's SQL editor.

create extension if not exists pgcrypto;
create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to authenticated, service_role;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '',
  city text not null default '',
  role text not null default 'member' check (role in ('member', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.artworks (
  id text primary key,
  title text not null,
  type_label text not null default 'Fine Art Print',
  category text not null default 'print' check (category in ('print', 'original')),
  price_amount integer not null default 0 check (price_amount >= 0),
  color text not null default '#8067e8',
  image_url text,
  year integer not null default extract(year from now())::integer,
  size_label text not null default '',
  edition_label text not null default '',
  description text not null default '',
  published boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.favorites (
  user_id uuid not null references auth.users(id) on delete cascade,
  artwork_id text not null references public.artworks(id) on delete cascade,
  price_at_save integer not null default 0,
  created_at timestamptz not null default now(),
  primary key (user_id, artwork_id)
);

create table if not exists public.price_history (
  id bigint generated by default as identity primary key,
  artwork_id text not null references public.artworks(id) on delete cascade,
  old_price integer not null,
  new_price integer not null,
  changed_at timestamptz not null default now(),
  changed_by uuid references auth.users(id) on delete set null
);

create index if not exists favorites_user_id_idx on public.favorites(user_id);
create index if not exists favorites_artwork_id_idx on public.favorites(artwork_id);
create index if not exists price_history_artwork_id_idx on public.price_history(artwork_id, changed_at desc);
create index if not exists artworks_published_order_idx on public.artworks(published, display_order);

create or replace function private.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.profiles
    where id = (select auth.uid()) and role = 'admin'
  );
$$;

grant execute on function private.is_admin() to authenticated, service_role;

create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'display_name', ''))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure private.handle_new_user();

create or replace function private.track_artwork_price()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if old.price_amount is distinct from new.price_amount then
    insert into public.price_history (artwork_id, old_price, new_price, changed_by)
    values (new.id, old.price_amount, new.price_amount, (select auth.uid()));
  end if;
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_artwork_price_changed on public.artworks;
create trigger on_artwork_price_changed
  before update on public.artworks
  for each row execute procedure private.track_artwork_price();

create or replace function private.protect_profile_role()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if old.role is distinct from new.role and not (select private.is_admin()) then
    raise exception 'Only an administrator can change account roles' using errcode = '42501';
  end if;
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_profile_role_change on public.profiles;
create trigger on_profile_role_change
  before update on public.profiles
  for each row execute procedure private.protect_profile_role();

alter table public.profiles enable row level security;
alter table public.artworks enable row level security;
alter table public.favorites enable row level security;
alter table public.price_history enable row level security;

create policy "Members read their own profile"
  on public.profiles for select to authenticated
  using ((select auth.uid()) = id or (select private.is_admin()));

create policy "Members update their own profile"
  on public.profiles for update to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

create policy "Published artworks are public"
  on public.artworks for select to anon, authenticated
  using (published = true);

create policy "Admins read all artworks"
  on public.artworks for select to authenticated
  using ((select private.is_admin()));

create policy "Admins create artworks"
  on public.artworks for insert to authenticated
  with check ((select private.is_admin()));

create policy "Admins update artworks"
  on public.artworks for update to authenticated
  using ((select private.is_admin()))
  with check ((select private.is_admin()));

create policy "Admins delete artworks"
  on public.artworks for delete to authenticated
  using ((select private.is_admin()));

create policy "Members read their favorites"
  on public.favorites for select to authenticated
  using ((select auth.uid()) = user_id);

create policy "Members add their favorites"
  on public.favorites for insert to authenticated
  with check ((select auth.uid()) = user_id);

create policy "Members remove their favorites"
  on public.favorites for delete to authenticated
  using ((select auth.uid()) = user_id);

create policy "Members read price changes for favorite artworks"
  on public.price_history for select to authenticated
  using (
    (select private.is_admin()) or exists (
      select 1 from public.favorites f
      where f.user_id = (select auth.uid()) and f.artwork_id = price_history.artwork_id
    )
  );

grant select on public.artworks to anon, authenticated;
grant select, insert, update, delete on public.artworks to authenticated;
grant select, update on public.profiles to authenticated;
grant select, insert, delete on public.favorites to authenticated;
grant select on public.price_history to authenticated;

insert into storage.buckets (id, name, public)
values ('artworks', 'artworks', true)
on conflict (id) do update set public = excluded.public;

create policy "Artwork images are public"
  on storage.objects for select to anon, authenticated
  using (bucket_id = 'artworks');

create policy "Admins upload artwork images"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'artworks' and (select private.is_admin()));

create policy "Admins update artwork images"
  on storage.objects for update to authenticated
  using (bucket_id = 'artworks' and (select private.is_admin()))
  with check (bucket_id = 'artworks' and (select private.is_admin()));

create policy "Admins delete artwork images"
  on storage.objects for delete to authenticated
  using (bucket_id = 'artworks' and (select private.is_admin()));
